"""Initial migration

Revision ID: cc1639cdd154
Revises: 
Create Date: 2023-02-11 21:17:36.165171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1639cdd154'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onwers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('document', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onwers_id'), 'onwers', ['id'], unique=True)
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.Enum('BLUE', 'GRAY', 'YELLOW', name='colorcar'), nullable=False),
    sa.Column('model', sa.Enum('CONVERTIBLE', 'HATCH', 'SEDAN', name='modelcar'), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['onwers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_index(op.f('ix_onwers_id'), table_name='onwers')
    op.drop_table('onwers')
    # ### end Alembic commands ###
