version: "3"
services:
    app-carford:
        build:
            context: .
            dockerfile: ./infra/Dockerfile
        command: sh -c "alembic upgrade head; gunicorn --bind 0.0.0.0:8000 application.server:app"
        depends_on:
            - db-carford
        volumes:
            - .:/app
        ports:
            - 8000:8000
    db-carford:
        image: postgres:14-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: db
        ports:
            - 5432:5432
        volumes:
            - database-carford:/var/lib/postgresql/data
volumes:
    database-carford: